### ISSUE TITLE
Bug: Add aws-lambda-powertools break my github workflow, "ModuleNotFoundError: No module named 'certifi'"

### ISSUE THREAD

**Issue by mobal** [awslabs/aws-lambda-powertools-python#1452]
### Expected Behaviour

If I add `aws-lambda-powertools` to my project (not imported even not used) it does not brea my workflow.

### Current Behaviour

During running `pytest` I got the following error: `ModuleNotFoundError: No module named 'certifi'`

### Code snippet

```python
There is no real "code snippet", please check "Debugging logs"
```

### Steps to Reproduce

Trigger my workflow

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

### Debugging logs

```python
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/pytest_httpx/__init__.py", line 3, in <module>
    import httpx
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/httpx/_client.py", line 10, in <module>
    from ._config import (
  File "/home/runner/.local/share/virtualenvs/personal-backend-service-vUakz4Jd/lib/python3.9/site-packages/httpx/_config.py", line 6, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'
Error: Process completed with exit code 1.
```

**Comment by mobal** [comment]
You can find my workflow logs here:

- the latest successful run: https://github.com/mobal/personal-backend-service/actions/runs/2857014897
- and about faulty running: https://github.com/mobal/personal-backend-service/actions/runs/2857006544

Thanks in advance!

**Comment by heitorlessa** [comment]
Thanks for reporting it @mobal. That looks like a dependency resolution issue as we don't use that dependency, but `httpx` at a quick glance.

For a quick test, I've just deployed a quick Lambda using the same pinned runtime dependencies you have, including `aws-lambda-powertools` - no issue here. I suspect your `pytest-httpx` is causing some issues. I'm gonna remove the bug label for now, and leave triage so we can try to reproduce that in the future to help out.

**Endpoint:** https://2060x4u5s0.execute-api.eu-west-1.amazonaws.com/Prod/hello/
**requirements.txt**

```
aws-lambda-powertools
pytest # just in case...
fastapi==0.78.0
uvicorn==0.17.6
mangum==0.15.0
pendulum==2.1.2
fastapi-camelcase==1.0.5
python-dotenv==0.20.0
boto3==1.24.2
python-slugify==6.1.2
pyjwt==2.4.0
pydantic[email]==1.9.1
httpx==0.23.0
```

**Comment by mobal** [comment]
Thanks for your help @heitorlessa, you were right. Removing `pytest-httpx` solves the problem. We are not talking about any bug here, I will continue to investigate the solution.

Thanks for your help once more!

**Comment by heitorlessa** [comment]
Awesome to hear, these things are tricky! Glad you're unblocked either way @mobal :)
