### ISSUE TITLE
Unable to install within a Python3 virtual env

### ISSUE THREAD

**Issue by nimbusscale** [awslabs/aws-lambda-powertools-python#183]
It appears that one of the dependencies of the `aws-lambda-powertools` package is the `future` package which throws an exception when trying to install the package in the Python3 venv. This is preventing of using this package in our lambdas which is all based on Python3.

## Expected Behavior
The following would work without error:
```
python3 -m venv ./venv
source  ./venv/bin/activate
pip install aws-lambda-powertools
```

## Current Behavior
```
$ pip install aws-lambda-powertools --no-cache
Collecting aws-lambda-powertools
  Downloading aws_lambda_powertools-1.6.1-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 5.1 MB/s 
Collecting aws-xray-sdk<3.0.0,>=2.5.0
  Downloading aws_xray_sdk-2.6.0-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 15.4 MB/s 
Collecting fastjsonschema<3.0.0,>=2.14.5
  Downloading fastjsonschema-2.14.5-py3-none-any.whl (21 kB)
Collecting jmespath<0.11.0,>=0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting boto3<2.0,>=1.12
  Downloading boto3-1.15.7-py2.py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 76.0 MB/s 
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 75.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/jjk3/PyCharmProjects/work/vmware/cset/pcas/slick/scratch/ptvenv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-teu935cv/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-teu935cv/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-twngn43t
         cwd: /tmp/pip-install-teu935cv/future/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jjk3/PyCharmProjects/work/vmware/cset/pcas/slick/scratch/ptvenv/lib/python3.7/site-packages/setuptools/__init__.py", line 5, in <module>
        import functools
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/functools.py", line 21, in <module>
        from collections import namedtuple
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/collections/__init__.py", line 27, in <module>
        from reprlib import recursive_repr as _recursive_repr
      File "/tmp/pip-install-teu935cv/future/src/reprlib/__init__.py", line 7, in <module>
        raise ImportError('This package should not be accessible on Python 3. '
    ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Environment
```
$ python --version
Python 3.7.5
$ pip --version
pip 20.2.3 from /home/jjk3/PyCharmProjects/work/vmware/cset/pcas/slick/scratch/ptvenv/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by heitorlessa** [comment]
Hey @nimbusscale, thanks for opening an issue.

By reading the trace stack, this points to an issue with Python 2 and Python 3, as we don't depend on future. Looking at the Poetry lock file, future is a transitive dependency of X-Ray SDK that we depend on.

When deploying the Lambda function itself using either Serverless Framework, does that work? 

A simple, sam build --use-container should tell, since it'll try installing Powertools in a fresh Docker container.

I recall seeing this issue before in Cloud9 when trying to install X-Ray SDK. It was due to pip trying to use site packages from Python2 despite a venv being activated in Python3.

You could also run this to double check while you have your venv activated:

python3 -E -S -c "import sys; print(sys.path)"

pip3 install aws-lambda-powertools

**Comment by nimbusscale** [comment]
Playing with this more it looks like I have something in PYTHONPATH that is causing the issue. IDK what, but when I unset the PYTHONPATH and then do the `pip install aws-lambda-powertools` it works fine.

Thanks for the breadcrumb. And maybe others will find this helpful in the future.
