### ISSUE TITLE
Bug: Adding tags to a route results in runtime error

### ISSUE THREAD

**Issue by danikenan** [awslabs/aws-lambda-powertools-python#3523]
### Expected Behaviour

Adding tags to a route should set the tags for that route and should not cause error at any stage.

### Current Behaviour

Adding tags to a route results in a runtime error: `TypeError: unhashable type: 'list'`

```
[ERROR] TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/package/lambda.py", line 10, in <module>
    from .v1.router import router as v1_router
  File "/var/task/package/v1/router.py", line 14, in <module>
    @router.get("/audience-anywhere", tags=["Audiences"])
  File "/opt/python/aws_lambda_powertools/event_handler/api_gateway.py", line 2159, in register_route
    self._routes_with_middleware[route_key] = []
   ```

### Code snippet

```python
@router.get("/audience-anywhere", tags=["Audiences"])
def audience_anywhere():
  return "OK"
```

or 

```
@app.get("/audience-anywhere", tags=["Audiences"])
def audience_anywhere():
  return "OK"
```
```


### Possible Solution

_No response_

### Steps to Reproduce

Simply add a tag to a route. See the snippets above.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

### Debugging logs

```python
[ERROR] TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/package/lambda.py", line 10, in <module>
    from .v1.router import router as v1_router
  File "/var/task/package/v1/router.py", line 14, in <module>
    @router.get("/audience-anywhere", tags=["Audiences"])
  File "/opt/python/aws_lambda_powertools/event_handler/api_gateway.py", line 2159, in register_route
    self._routes_with_middleware[route_key] = []
   ```
```

**Comment by MCR2019** [comment]
@danikenan - are you using the latest version 2.30.1?

There was a fix which looks related to this -> https://github.com/aws-powertools/powertools-lambda-python/issues/3506

**Comment by rubenfonseca** [comment]
@danikenan as @MCR2019 said, can you please confirm us which version of Powertools are you using?

**Comment by rubenfonseca** [comment]
I'm closing this issue for the time being, please feel free to reopen if you still have a problem!
