### ISSUE TITLE
Bug: APIGatewayProxyEventV2.decoded_body should not cause KeyError

### ISSUE THREAD

**Issue by aahung** [awslabs/aws-lambda-powertools-python#3706]
### Expected Behaviour

For event of type `APIGatewayProxyEventV2`, `event.decoded_body` or `event.json_body` (which calls the former) could result in `KeyError` when there is no body. 

### Current Behaviour

<img width="1159" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3804518/027790dd-c187-4173-a1e2-974bc9feb7a7">

### Code snippet

```python
`event.decoded_body` or `event.json_body`
```

### Possible Solution

- `event.decoded_body` should return empty string or `None`
- `event.json_body` should raise `JSONDecodeError`

### Steps to Reproduce

As described. 

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Hey @aahung! Thanks for reporting this bug. You're right, we should use `body: str = self.body` instead of `body: str = self["body"]` in this line https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/data_classes/common.py#L149.

Do you want to send a PR to fix this? We would love it.

Thanks

**Comment by heitorlessa** [comment]
Hi @aahung could you share how you ended up with the `body` key missing in the first place? Was this an actual request from API Gateway HTTP API, **or** a fake event?

Thank you

**Comment by isaacasancheza** [comment]
Hello there,

In my case it's an actual request from API Gateway HTTP API. Sending a POST without body throws the error (in my case using Postman with Body as none). I'm using `aws_lambda_powertools.event_handler.APIGatewayHttpResolver` with `enable_validation=True`.

```python3
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/event_handler/api_gateway.py", line 2002, in _call_route
    route(router_middlewares=self._router_middlewares, app=self, route_arguments=route_arguments),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/event_handler/api_gateway.py", line 400, in __call__
    return self._middleware_stack(app)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/event_handler/api_gateway.py", line 1291, in __call__
    return self.current_middleware(app, self.next_middleware)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/event_handler/middlewares/base.py", line 121, in __call__
    return self.handler(app, next_middleware)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/event_handler/middlewares/openapi_validation.py", line 117, in handler
    received_body=self._get_body(app),
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/event_handler/middlewares/openapi_validation.py", line 243, in _get_body
    return app.current_event.json_body
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/common.py", line 153, in json_body
    return self._json_deserializer(self.decoded_body)
                                   ^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/common.py", line 158, in decoded_body
    body: str = self["body"]
                ~~~~^^^^^^^^
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/common.py", line 32, in __getitem__
    return self._data[key]
           ~~~~~~~~~~^^^^^
KeyError: 'body'
```
