### ISSUE TITLE
Event validation error with SNS Event

### ISSUE THREAD

**Issue by aquisx** [awslabs/aws-lambda-powertools-python#457]
I'm facing currently a validation error using the Lambda Powertools Python libary in a lambda function. 
The validation command is:
```


 from create.utils.inputSchemas import input
from aws_lambda_powertools.utilities.validation import validator, envelopes
@validator(inbound_schema=input, envelope=envelopes.SNS)
def lambda_handler(event, context):

    [...]
```

For me everything seems right but I'm getting the following error:

```
[ERROR] JMESPathTypeError: In function powertools_json(), invalid type for value: {'version': '0', 'id': '0000000-0000-0000-0000-00000000', 'detail-type': 'EC2 Instance State-change Notification', 'source': 'aws.ec2', 'account': '0000000000', 'time': '2021-05-18T14:14:12Z', 'region': 'eu-central-1', 'resources': ['arn:aws:ec2:eu-central-1:000000000:instance/i-0000000000'], 'detail': {'instance-id': 'i-000000000', 'state': 'terminated'}}, expected one of: ['string'], received: "object"
Traceback (most recent call last):
  File "/var/task/aws_lambda_powertools/middleware_factory/factory.py", line 133, in wrapper
    response = middleware()
  File "/var/task/aws_lambda_powertools/utilities/validation/validator.py", line 119, in validator
    event = unwrap_event_from_envelope(data=event, envelope=envelope, jmespath_options=jmespath_options)
  File "/var/task/aws_lambda_powertools/utilities/validation/base.py", line 65, in unwrap_event_from_envelope
    return jmespath.search(envelope, data, options=jmespath.Options(**jmespath_options))
  File "/var/task/jmespath/__init__.py", line 23, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/var/task/jmespath/parser.py", line 509, in search
    result = interpreter.visit(self.parsed, value)
  File "/var/task/jmespath/visitor.py", line 94, in visit
    return method(node, *args, **kwargs)
  File "/var/task/jmespath/visitor.py", line 269, in visit_pipe
    result = self.visit(node, result)
  File "/var/task/jmespath/visitor.py", line 94, in visit
    return method(node, *args, **kwargs)
  File "/var/task/jmespath/visitor.py", line 171, in visit_function_expression
    return self._functions.call_function(node['value'], resolved_args)
  File "/var/task/jmespath/functions.py", line 80, in call_function
    self._validate_arguments(resolved_args, signature, function_name)
  File "/var/task/jmespath/functions.py", line 91, in _validate_arguments
    return self._type_check(args, signature, function_name)
  File "/var/task/jmespath/functions.py", line 97, in _type_check
    self._type_check_single(actual[i], allowed_types,
  File "/var/task/jmespath/functions.py", line 111, in _type_check_single
    raise exceptions.JMESPathTypeError(END RequestId: 92c00173-eb6c-4035-b3f7-80f009e95035

```

That doesn't make any sense for me, because why is validate expecting a string, usually event is a dict object and I can't find any information is the documentation.

The event for testing the validation is:

```
{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:Subscriptionname",
      "Sns": {
        "Type": "Notification",
        "MessageId": "00000000-0000-0000-0000-000000000",
        "TopicArn": "TOPICARN",
        "Subject": "None",
        "Message": {
          "version": "0",
          "id": "00000000-0000-0000-0000-000000000000",
          "detail-type": "EC2 Instance State-change Notification",
          "source": "aws.ec2",
          "account": "000000000000",
          "time": "2021-05-18T14:14:12Z",
          "region": "eu-central-1",
          "resources": [
            "arn:aws:ec2:eu-central-1:000000000000:instance/i-00000000000000000"
          ],
          "detail": {
            "instance-id": "i-00000000000000000",
            "state": "terminated"
          }
        },
        "Timestamp": "2021-05-18T15:55:35.862Z",
        "SignatureVersion": "1",
        "Signature": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000==",
        "SigningCertUrl": "https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-00000000000000000000000000000000.pem",
        "UnsubscribeUrl": "https://sns.eu-central-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-central-1:00000000000000000000:00000000-0000-0000-0000-000000000000",
        "MessageAttributes": {}
      }
    }
  ]
}
```

The validation scheme is:
```
   {
        "definitions": {},
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://example.com/object1622542263.json",
        "title": "Root",
        "type": "object",
        "required": [
            "version",
            "id",
            "detail-type",
            "source",
            "account",
            "time",
            "region",
            "resources",
            "detail"
        ],
        "properties": {
            "version": {
                "$id": "#root/version",
                "title": "Version",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "id": {
                "$id": "#root/id",
                "title": "Id",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "detail-type": {
                "$id": "#root/detail-type",
                "title": "Detail-type",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "source": {
                "$id": "#root/source",
                "title": "Source",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "account": {
                "$id": "#root/account",
                "title": "Account",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "time": {
                "$id": "#root/time",
                "title": "Time",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "region": {
                "$id": "#root/region",
                "title": "Region",
                "type": "string",
                "default": "",
                "pattern": "^.*$"
            },
            "resources": {
                "$id": "#root/resources",
                "title": "Resources",
                "type": "array",
                "default": [],
                "items": {
                    "$id": "#root/resources/items",
                    "title": "Items",
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                }
            },
            "detail": {
                "$id": "#root/detail",
                "title": "Detail",
                "type": "object",
                "required": [
                    "instance-id",
                    "state"
                ],
                "properties": {
                    "instance-id": {
                        "$id": "#root/detail/instance-id",
                        "title": "Instance-id",
                        "type": "string",
                        "default": "",
                        "pattern": "^.*$"
                    },
                    "state": {
                        "$id": "#root/detail/state",
                        "title": "State",
                        "type": "string",
                        "default": "",
                        "pattern": "^.*$"
                    }
                }
            }

        }
    }
```

Is it a bug or my mistake?

**Comment by heitorlessa** [comment]
Hey @aquisx - Thanks for raising this!

How did you create the testing event?

By looking at the event, I'd guess you have `EventBridge -> SNS -> Lambda`. In that case, EventBridge will serialize the EC2 event and pass a Payload to SNS - hence why it's failing because SNS doesn't send the payload message as a dictionary but as a JSON string.

I've just re-created that to double check in case SNS changed the contract - it confirms EventBridge sends as a JSON string[1], which works as expected since Validator will deserialize the JSON string with the envelope feature before it applies schema validation:

Hope that helps!

---

**Your test event with the payload now serialized - this works**

```json
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:Subscriptionname",
            "Sns": {
                "Type": "Notification",
                "MessageId": "00000000-0000-0000-0000-000000000",
                "TopicArn": "TOPICARN",
                "Subject": "None",
                "Message": '{"version": "0", "id": "00000000-0000-0000-0000-000000000000", "detail-type": "EC2 Instance State-change Notification", "source": "aws.ec2", "account": "000000000000", "time": "2021-05-18T14:14:12Z", "region": "eu-central-1", "resources": ["arn:aws:ec2:eu-central-1:000000000000:instance/i-00000000000000000"], "detail": {"instance-id": "i-00000000000000000", "state": "terminated"}}'
                ,
                "Timestamp": "2021-05-18T15:55:35.862Z",
                "SignatureVersion": "1",
                "Signature": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000==",
                "SigningCertUrl": "https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-00000000000000000000000000000000.pem",
                "UnsubscribeUrl": "https://sns.eu-central-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-central-1:00000000000000000000:00000000-0000-0000-0000-000000000000",
                "MessageAttributes": {},
            },
        }
    ]
}
```

[1] **Raw JSON event from EventBridge->SNS->Lambda**

```json
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:eu-west-1:123456789012:powertools457-issue:08d71ab7-45d0-4a14-a3ba-58a7ee1d5bc0",
            "Sns": {
                "Type": "Notification",
                "MessageId": "21e66291-ea41-530e-bfd6-3ba0886e1211",
                "TopicArn": "arn:aws:sns:eu-west-1:123456789012:powertools457-issue",
                "Subject": null,
                "Message": "{\"version\":\"0\",\"id\":\"ca6432a8-89b0-0007-8e23-c57c29435065\",\"detail-type\":\"EC2 Instance State-change Notification\",\"source\":\"aws.ec2\",\"account\":\"123456789012\",\"time\":\"2021-06-02T10:39:43Z\",\"region\":\"eu-west-1\",\"resources\":[\"arn:aws:ec2:eu-west-1:123456789012:instance/i-0aef86944196d09b7\"],\"detail\":{\"instance-id\":\"i-0aef86944196d09b7\",\"state\":\"running\"}}",
                "Timestamp": "2021-06-02T10:39:43.471Z",
                "SignatureVersion": "1",
                "Signature": "cxBQDU+k/SXYezXEIfiwW4dEdFOlW3T6QLq1qEeFCqzJTWacMttXXRwRLpj3NU1bjD1dDdgOqhZZIql//EXIQALiAJkoi3mo0Cfn6kuFTyfZ1N4mlnehbHC+scOGbo8K0gafuVZJJj3nNCHqsb7WvrKAUkajCerunoa0tQcwJchQJsZf/Th8jUlARM8xc97n5n7p0rkdQGT77/dRAXG2YtBZuwpxwQCdtrUrvaD7vFiF1aVzCy8jj4PLuN8jcLZWQTyvLY1aZDKEm/9TR6H87g6aRn5M/d8Tqrdov7cgoRJlYuZWL+Kk0CBybramLguGNWpTPrxeWpQ8l8DzvH/vAQ==",
                "SigningCertUrl": "https://sns.eu-west-1.amazonaws.com/SimpleNotificationService-010a507c1833636cd94bdb98bd93083a.pem",
                "UnsubscribeUrl": "https://sns.eu-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-west-1:123456789012:powertools457-issue:08d71ab7-45d0-4a14-a3ba-58a7ee1d5bc0",
                "MessageAttributes": {}
            }
        }
    ]
```

**Comment by heitorlessa** [comment]
Closing this as we haven't heard from you - feel free to reopen otherwise.

Thank you
