### ISSUE TITLE
Bug: logger errors

### ISSUE THREAD

**Issue by tb102122** [awslabs/aws-lambda-powertools-python#4782]
### Expected Behaviour

Logger successful initiated.

### Current Behaviour

logger setup phase is not running successful

### Code snippet

```python
from aws_lambda_powertools import Logger

logger = Logger(service="cx_claims")

def lambda_handler(event, context):
    logger.debug("Received event: " + json.dumps(event, indent=2))
    logger.info("test")
    return True
```

### Steps to Reproduce

set env var to AWS_LAMBDA_LOG_LEVEL = "INFO" invoke lambda

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

### Debugging logs

```python
START RequestId: XXX Version: $LATEST
--- Logging error ---
Traceback (most recent call last):
File "/var/lang/lib/python3.12/logging/__init__.py", line 1160, in emit
msg = self.format(record)
^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.12/logging/__init__.py", line 999, in format
return fmt.format(record)
^^^^^^^^^^^^^^^^^^
File "/opt/python/aws_lambda_powertools/logging/formatter.py", line 170, in format
formatted_log["message"] = self._extract_log_message(log_record=record)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/aws_lambda_powertools/logging/formatter.py", line 283, in _extract_log_message
return log_record.getMessage()
^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.12/logging/__init__.py", line 392, in getMessage
msg = msg % self.args
~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
File "/var/runtime/bootstrap.py", line 63, in <module>
main()
File "/var/runtime/bootstrap.py", line 60, in main
awslambdaricmain.main([os.environ["LAMBDA_TASK_ROOT"], os.environ["_HANDLER"]])
File "/var/lang/lib/python3.12/site-packages/awslambdaric/__main__.py", line 21, in main
bootstrap.run(app_root, handler, lambda_runtime_api_addr)
File "/var/lang/lib/python3.12/site-packages/awslambdaric/bootstrap.py", line 499, in run
handle_event_request(
File "/var/lang/lib/python3.12/site-packages/awslambdaric/bootstrap.py", line 188, in handle_event_request
response = request_handler(event, lambda_context)
```

**Comment by leandrodamascena** [comment]
Hello @tb102122! Thanks for reporting this issue!

I was looking at the error and the code and I think the problem is related to the type of data you are trying to log in the `logger.debug("Received event: " + json.dumps(event, indent=2))` line. 

I have some questions to help me understand better the problem:

1 - Are you using custom runtime or docker images with Lambda?
2 - Can you share with me the payload? Please remove any sensitive data.
3 - What the experience you're trying to have here? You want INFO level, DEBUG level or switch between them when executing your Lambda?

Thanks

**Comment by tb102122** [comment]
sorry yes you are right the formatting was wrong.
